name: Update Repository
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  pull-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is fetched

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Remote and Fetch Latest Changes
        run: |
          git remote add upstream https://github.com/colbyhemond/quickstart-site.git
          git fetch upstream main

      - name: Merge Remote Changes
        run: |
          git checkout main
          git merge --no-edit upstream/main || echo "No new changes to merge."

      - name: Push Changes
        run: |
          git push origin main
